<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('users')->delete();
        
        DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'username' => 'admin',
                'email' => 'admin@admin.com',
                'password' => '$2y$10$BIleDgvtDHkssNv53xw2aO13VwBTYJ1FZmKD4GlQrMCUbk1rtDcBe',
                'bio' => 'bio',
                'avatar' => 'uploads/6755c73c03ed1-image.jpg',
                'banner' => 'uploads/6755c744290a7-image.jpg',
                'is_admin' => 1,
                'socialProvider' => NULL,
                'created_at' => '2024-11-29 15:33:15',
                'updated_at' => '2024-12-08 16:20:20',
            ),
            1 => 
            array (
                'id' => 2,
                'username' => 'roger_51',
                'email' => '4hogrlwp4@talk21.com',
                'password' => '$2y$10$hJ5Vz8XeYuSfBfbOihK95.jkcSDeI1FX4ECIj3Y5IBUTwOsNfBzaW',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 1,
                'socialProvider' => NULL,
                'created_at' => '2024-11-29 17:33:15',
                'updated_at' => '2024-12-04 15:34:10',
            ),
            2 => 
            array (
                'id' => 3,
                'username' => 'luisangel_72',
                'email' => 'ivl77yaca@lycos.es',
                'password' => '$2y$10$TO3VRIrEOBFVnshlgG0oYOzfdZFMJ9A1OjnpQ7tIeBLeU1CYshZCS',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2024-11-29 17:33:15',
                'updated_at' => '2024-11-29 17:33:15',
            ),
            3 => 
            array (
                'id' => 4,
                'username' => 'martin_71',
                'email' => '47vjms9v@talk21.com',
                'password' => '$2y$10$R2aFxfkatEfZn3.Z3hsRJeDlaZWb6syKgfDK/04R1LqT3SwDnmYqO',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2024-11-29 17:33:15',
                'updated_at' => '2024-11-29 17:33:15',
            ),
            4 => 
            array (
                'id' => 5,
                'username' => 'anaisabel_82',
                'email' => '661y5fmif@witty.com',
                'password' => '$2y$10$tW6cDQgrP2zI3xxeVpbxj.4S.s/7eb.kHeJ0nGSpwQzQEcv4EGJRu',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2024-11-29 17:33:15',
                'updated_at' => '2024-11-29 17:33:15',
            ),
            5 => 
            array (
                'id' => 6,
                'username' => 'ariadna_82',
                'email' => 'qp31jzyc3r@aol.com',
                'password' => '$2y$10$JlmbnTbgibv43CU15geRsOYm9IlD7RoDaVLHWy6E.gqQax63RZZ6a',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2024-11-29 17:33:15',
                'updated_at' => '2024-11-29 17:33:15',
            ),
            6 => 
            array (
                'id' => 8,
                'username' => 'Yisustex',
                'email' => 'yisustex@gmail.com',
                'password' => '$2y$10$OCmFowAE2ZM0QAU/v2WV7u9J463A6KcMLtBo8Ov9352ZHwgMrRh5q',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2024-11-29 17:33:15',
                'updated_at' => '2024-11-29 17:33:15',
            ),
            7 => 
            array (
                'id' => 16,
                'username' => 'Mony6YoRespirareTodosLoVereis',
                'email' => 'kurumichan491@gmail.com',
                'password' => '$2y$10$ZImbgS6XaaPRwNHveWnfW.Py2QPxXB4rHUYoDP6KfxQ5CY/QdQBL2',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2024-12-01 19:00:49',
                'updated_at' => '2024-12-01 19:09:55',
            ),
            8 => 
            array (
                'id' => 17,
                'username' => 'ADMlN',
                'email' => 'a.gomez9@sapalomera.cat',
                'password' => '$2y$10$HZ8a1UmUkdfUB/NcLFN5PuLXvweZANdge.QDvnTZYVVU34D7eJ1Sq',
                'bio' => NULL,
                'avatar' => 'uploads/674dd403cd611-image.jpg',
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2024-12-02 15:35:47',
                'updated_at' => '2024-12-02 15:36:35',
            ),
            9 => 
            array (
                'id' => 18,
                'username' => 'Pancracio',
                'email' => 'ravirubio2621@gmail.com',
                'password' => '$2y$10$RNf4oip9KZPzDgD4iXuMYuYkU4XjOirODK/iH8RYgxmQiOKCqarnq',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2024-12-02 15:36:26',
                'updated_at' => '2024-12-02 15:36:26',
            ),
            10 => 
            array (
                'id' => 20,
                'username' => 'CosmicComet_c5b752',
                'email' => 'danielagames0608@gmail.com',
                'password' => '',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => 'github',
                'created_at' => '2024-12-04 01:36:54',
                'updated_at' => '2024-12-04 01:36:54',
            ),
            11 => 
            array (
                'id' => 26,
                'username' => 'Dios',
                'email' => 'admin@oni.cat',
                'password' => '$2y$10$IHHM0tYSmVflirg9Y5z4t.rYoKxkcY6w2/.FiChlUnJ6vMDjG8aCi',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2024-12-04 15:23:15',
                'updated_at' => '2024-12-04 16:59:34',
            ),
            12 => 
            array (
                'id' => 28,
                'username' => 'ElectricWanderer_b0202e',
                'email' => 'santionieva@gmail.com',
                'password' => '',
                'bio' => 'Eri gay?',
                'avatar' => 'uploads/675078f694069-image.jpg',
                'banner' => 'uploads/675079281acb5-image.jpg',
                'is_admin' => 0,
                'socialProvider' => 'github',
                'created_at' => '2024-12-04 15:28:31',
                'updated_at' => '2024-12-04 15:45:44',
            ),
            13 => 
            array (
                'id' => 29,
                'username' => 'LunarEclipse_a1c746',
                'email' => 'mmilancastro491@gmail.com',
                'password' => '',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => 'github',
                'created_at' => '2024-12-04 15:32:43',
                'updated_at' => '2024-12-04 15:32:43',
            ),
            14 => 
            array (
                'id' => 30,
                'username' => 'VelvetComet_4f1498',
                'email' => 'milan.castro.monica@iescamas.es',
                'password' => '',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => 'google',
                'created_at' => '2024-12-04 17:09:12',
                'updated_at' => '2024-12-04 17:09:12',
            ),
            15 => 
            array (
                'id' => 31,
                'username' => 'LunarWanderer_484c91',
                'email' => 'torres10213@gmail.com',
                'password' => '',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => 'google',
                'created_at' => '2024-12-07 16:41:50',
                'updated_at' => '2024-12-07 16:41:50',
            ),
            16 => 
            array (
                'id' => 32,
                'username' => 'ElectricComet_7a1daa',
                'email' => 'd.gamez@sapalomera.cat',
                'password' => '',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => 'google',
                'created_at' => '2025-01-08 18:55:53',
                'updated_at' => '2025-01-08 18:55:53',
            ),
            17 => 
            array (
                'id' => 33,
                'username' => 'VelvetEclipse_6dbfbf',
                'email' => 'j.gomez4@sapalomera.cat',
                'password' => '',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => 'google',
                'created_at' => '2025-01-14 15:46:54',
                'updated_at' => '2025-01-14 15:46:54',
            ),
            18 => 
            array (
                'id' => 34,
                'username' => 'xgallego',
                'email' => 'xgallego@sapalomera.cat',
                'password' => '$2y$10$nLj/twbHVB6TSuJVvQbbH.JgVJnCiGS2Ub2s5JaySNyP9kOeFqaAW',
                'bio' => NULL,
                'avatar' => 'uploads/6788059e23abc-image.jpg',
                'banner' => 'uploads/678805cd80c10-image.jpg',
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-01-15 18:59:03',
                'updated_at' => '2025-01-15 19:00:29',
            ),
            19 => 
            array (
                'id' => 35,
                'username' => 'molOhHCINDUyJSL',
                'email' => 'anocitof075@gmail.com',
                'password' => '$2y$10$55D4OrhkSWXJaH5IRTpNAOY5rCIsGx5KmjWfzOoCnh80H.G4O4mrK',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-02-21 17:41:02',
                'updated_at' => '2025-02-21 17:41:02',
            ),
            20 => 
            array (
                'id' => 36,
                'username' => 'xaxebfWNRwilK',
                'email' => 'abraxasuyecho@gmail.com',
                'password' => '$2y$10$k7cwvQEf9VGwYE29GQjEeeQIgRWqdARrNASph0Ef/f0PlKZ21JCFe',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-02-24 04:33:24',
                'updated_at' => '2025-02-24 04:33:24',
            ),
            21 => 
            array (
                'id' => 37,
                'username' => 'GqpDHqxGunSXyDf',
                'email' => 'mementou4nexus41@gmail.com',
                'password' => '$2y$10$ROPJTvDrsQPASOzoI/j97.wFhfVpektXgU9oXmRW9yjUvUmA66bTO',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-02-25 06:11:26',
                'updated_at' => '2025-02-25 06:11:26',
            ),
            22 => 
            array (
                'id' => 38,
                'username' => 'TwkYyuRkxV',
                'email' => 'aekismetalchemy@gmail.com',
                'password' => '$2y$10$Jz8g6U.29tvYLkFZXg27pemguXhqrf7rnWEu4Lj5gqcf/8sXCLDN.',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-02-26 07:02:14',
                'updated_at' => '2025-02-26 07:02:14',
            ),
            23 => 
            array (
                'id' => 39,
                'username' => 'JpCAlmYh',
                'email' => 'sxpxjmrqojjutxeqr@yahoo.com',
                'password' => '$2y$10$qgVZBC49/Roeb8HdQcGuUu.wSr8IB7ZesfDERcf8wBABzA78RDfSO',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-03-01 00:33:34',
                'updated_at' => '2025-03-01 00:33:34',
            ),
            24 => 
            array (
                'id' => 40,
                'username' => 'ZdjDHiZXQRrEBd',
                'email' => 'riveracharlzr5@gmail.com',
                'password' => '$2y$10$zwnc/RB.1sPzK1obWhLnseE7dqy4Pb8Uc6rNGMxSeZRUMjtfcsMx2',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-03-02 08:07:32',
                'updated_at' => '2025-03-02 08:07:32',
            ),
            25 => 
            array (
                'id' => 41,
                'username' => 'JBQMMiseIJlgRyK',
                'email' => 'astuartlv4@gmail.com',
                'password' => '$2y$10$IcocbK6QcDdNCKII653hCOZHetgYuFUVrPB5UsVW1bUvZ2PSO9oyS',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-03-06 05:54:06',
                'updated_at' => '2025-03-06 05:54:06',
            ),
            26 => 
            array (
                'id' => 42,
                'username' => 'BcvuhAdhrwLM',
                'email' => 'djadincje@gmail.com',
                'password' => '$2y$10$CgbW4cImVqJqRfq04stfgOwLZu4iR4mEn0/JLKbNn.JlzS8wFSFjG',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-03-08 09:11:32',
                'updated_at' => '2025-03-08 09:11:32',
            ),
            27 => 
            array (
                'id' => 43,
                'username' => 'JmOtzzMQilzzEi',
                'email' => 'roismossry2001@gmail.com',
                'password' => '$2y$10$hOhSm6LcFwUmxS3gcCQERuRJe0ZNbVqhuET1Kv6akK0hwG.SoA1Ji',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-03-16 10:01:53',
                'updated_at' => '2025-03-16 10:01:53',
            ),
            28 => 
            array (
                'id' => 44,
                'username' => 'CidCmBuIO',
                'email' => 'diggwolfe26@gmail.com',
                'password' => '$2y$10$0UTAWHzE9sOmTyTlj6/tVOtDMce95e97yR0DSNMqpIrtV21FwXq3.',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-03-17 05:13:35',
                'updated_at' => '2025-03-17 05:13:35',
            ),
            29 => 
            array (
                'id' => 45,
                'username' => 'IUIyefXjTl',
                'email' => 'tardy_ayye614161@yahoo.com',
                'password' => '$2y$10$fh1g8PLZGon9sDQIaH2HyO6ekX2Pu77jOVQyr3TW.vQ5iYHRKAkii',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-03-19 15:24:28',
                'updated_at' => '2025-03-19 15:24:28',
            ),
            30 => 
            array (
                'id' => 46,
                'username' => 'tXLGUOoqPNaIb',
                'email' => 'karlayalambert@gmail.com',
                'password' => '$2y$10$3e/mTNl.MtclCYVwDBVEAO3DCW4v/WQkovTHy3hbK2n8ZgB0PFFyW',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-03-21 22:11:18',
                'updated_at' => '2025-03-21 22:11:18',
            ),
            31 => 
            array (
                'id' => 47,
                'username' => 'tSGwJwVwG',
                'email' => 'harperaselina@gmail.com',
                'password' => '$2y$10$mrztXDxGO5oUzbkJRAsuO.ZkPpbsM6IoNEwo/njt6cT.0c1CFGeLm',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-03-22 12:45:15',
                'updated_at' => '2025-03-22 12:45:15',
            ),
            32 => 
            array (
                'id' => 48,
                'username' => 'WceiSZHxr',
                'email' => 'triyatownsendh20@gmail.com',
                'password' => '$2y$10$NYex4GeSJsbnj8dqRW4HrOt.m67gB6zl8RrurhgfK0KCohcdE5jXO',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-03-23 05:12:23',
                'updated_at' => '2025-03-23 05:12:23',
            ),
            33 => 
            array (
                'id' => 49,
                'username' => 'iQjMCWBsiQhBVRu',
                'email' => 'walkermichael723832@yahoo.com',
                'password' => '$2y$10$uNSuUNnvLAq7eHLk1BWzXOreKMluR.LBhnulSSx7JGo3d3wMWDfcK',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-03-23 20:29:19',
                'updated_at' => '2025-03-23 20:29:19',
            ),
            34 => 
            array (
                'id' => 50,
                'username' => 'RfTQPAjwWC',
                'email' => 'mondymark1982@yahoo.com',
                'password' => '$2y$10$giz9D09JjDTs.cebjUgb5ORZzra2oIdByZw0K6ELjfh4sZNMumkNi',
                'bio' => NULL,
                'avatar' => NULL,
                'banner' => NULL,
                'is_admin' => 0,
                'socialProvider' => NULL,
                'created_at' => '2025-03-28 15:24:34',
                'updated_at' => '2025-03-28 15:24:34',
            ),
        ));
        
        
    }
}