[phases.setup]
commands = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan migrate --force"
]

[phases.build]
commands = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[services.web]
command = "php artisan serve --host=0.0.0.0 --port=$PORT"
